# Generated by Django 4.0.4 on 2022-05-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0004_commande_address_commande_email_commande_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='commande',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='commande',
            name='items',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='commande',
            name='nom',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='commande',
            name='pays',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='commande',
            name='ville',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='commande',
            name='zipcode',
            field=models.CharField(max_length=300),
        ),
    ]
