# Generated by Django 4.0.4 on 2022-05-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0005_alter_commande_address_alter_commande_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='totalCde',
            new_name='total',
        ),
    ]
