# Generated by Django 4.0.4 on 2022-05-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0007_alter_categorie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='type',
            field=models.CharField(choices=[('Enf', 'Enfant'), ('Ad', 'Adulte'), ('tout', 'Tout le monde')], default='tout', max_length=200),
        ),
    ]
