# Generated by Django 4.0.4 on 2022-05-25 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Realisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('nationalite', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('type', models.CharField(choices=[('Enf', 'Enfant'), ('Adu', 'Adulte'), ('Tout', 'Tout le monde')], default='Tout', max_length=20)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='film.categorie')),
                ('realisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='film.realisateur')),
            ],
        ),
    ]
